name=input("what is your name?")
print(f"Hello {name}!")
print("how are you today")
input("")
print("great me to!")
input("")
hobbies=input("what are your hobbies?!")
print(f"wow! That sound super fun")
print("what school do you go to!")
input("")
print("Thats an awesome school")
input("")
print("Whats your birthday?")
input("")
print("Nice! Mines August 21st")
print("How old are you?")
input("")
print("Very cool!")
print("Whats your favorite season?")
input("")
print("Nice!")
print("Well I hope you have a great rest of your day!")
print("Bye!!!")
input("")