name=input("what is your name?")
print(f"Hello {name}!")
print("how are you today")
input("")
print("great")
input("")
hobbies=input("what are your hobbies?!")
print(f"wow! That sound super fun")
print("what school do you go to!")
input("")
